workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create missing Flutter iOS platform files
        script: |
          flutter create . --platforms=ios
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
